syntax = "proto3";

package delivery;

service DeliveryService {
  rpc CreateDelivery(CreateDeliveryRequest)
      returns (CreateDeliveryResponse);

  rpc GetDelivery(GetDeliveryRequest)
      returns (GetDeliveryResponse);

  rpc GetDeliveryByOrder(GetDeliveryByOrderRequest)
      returns (GetDeliveryByOrderResponse);
}

message CreateDeliveryRequest {
  string order_id = 1;
}

message CreateDeliveryResponse {
  string delivery_id = 1;
  string order_id = 2;
  string status = 3;
}

message GetDeliveryRequest {
  string delivery_id = 1;
}

message GetDeliveryResponse {
  string delivery_id = 1;
  string order_id = 2;
  string status = 3;
}

message GetDeliveryByOrderRequest {
  string order_id = 1;
}

message GetDeliveryByOrderResponse {
  string delivery_id = 1;
  string order_id = 2;
  string status = 3;
}